lastfm_tag_categories = [
    ["calm", "comfort", "quiet", "serene", "mellow", "chill out", "calm down", "calming", "chillout", "comforting", "content", "cool down", "mellow music", "mellow rock", "peace of mind", "quietness", "relaxation", "serenity", "solace", "soothe", "soothing", "still", "tranquil", "tranquility", "tranquillity"],
    ["sad", "sadness", "unhappy", "melancholic", "melancholy", "feeling sad", "mood: sad - slightly", "sad song"],
    ["happy", "glad", "happiness", "happy songs", "happy music", "mood: happy"],
    ["romantic", "romantic music"],
    ["gleeful", "upbeat", "high spirits", "zest", "enthusiastic", "buoyancy", "elation", "mood: upbeat"],
    ["gloomy", "depressed", "blue", "dark", "depressive", "dreary", "gloom", "darkness", "depress", "depression", "depressing"],
    ["angry", "anger", "choleric", "fury", "outraged", "rage", "angry music"],
    ["mournful", "grief", "heartbreak", "sorrow", "sorry", "doleful", "heartache", "heartbreaking", "heartsick", "lachrymose", "mourning", "plaintive", "regret", "sorrowful"],
    ["dreamy"],
    ["cheerful", "cheer up", "festive", "jolly", "jovial", "merry", "cheer", "cheering", "cheery", "get happy", "rejoice", "songs that are cheerful", "sunny"],
    ["brooding", "contemplative", "meditative", "reflective", "broody", "pensive", "pondering", "wistful"],
    ["aggressive", "aggression"],
    ["anxious", "angst", "anxiety", "jumpy", "nervous", "angsty"],
    ["confident", "encouraging", "encouragement", "optimism", "optimistic"],
    ["hopeful", "desire", "hope", "mood: hopeful"],
    ["earnest", "heartfelt"],
    ["cynical", "pessimism", "pessimistic", "weltschmerz", "cynical/sarcastic"],
    ["exciting", "excitement", "exhilarating", "thrill", "ardor", "stimulating", "thrilling", "titillating"]
]